### ISSUE TITLE
apply in common UI's

### ISSUE THREAD

**Issue by moonshinegloss** [rohitgandikota/sliders#2] opened 2023-11-22 17:24 UTC
is there a way to load this into a11 or comfyUI? or would this need some special plugin to work? I tried to load it as an embedding or hypernetwork, but neither worked; thanks

**Comment by rohitgandikota** [comment] 2023-11-22 20:56
So the lora adaptors we trained are for visual layers in UNET (all layers except cross attentions). I believe such adaptors are not supported by a11 or comfyUI. We can get it touch with the developers to discuss potential support of our sliders.

For now, we are working on a colab demo for training and using our sliders.

**Comment by hkunzhe** [comment] 2023-11-23 13:19
> So the lora adaptors we trained are for visual layers in UNET (all layers except cross attentions). I believe such adaptors are not supported by a11 or comfyUI. We can get it touch with the developers to discuss potential support of our sliders.
> 
> For now, we are working on a colab demo for training and using our sliders.

Hi, great work! I've tried to load the pre-trained xl sliders as Lora in Web UI. It seems to work normally. This was also verified by ComfyUI. https://github.com/comfyanonymous/ComfyUI/issues/2028

**Comment by rohitgandikota** [comment] 2023-11-23 15:26
Yes, but the inference methods we introduce might not be implemented in the UIs. The technique we use in inference is quite a bit useful to allow precise editing.

**Comment by hkunzhe** [comment] 2023-11-23 15:51
@rohitgandikota By comparing the results with your inference code and the Web UI, it is indeed confirmed that the SDEdit tricks can better maintain the stability of other attributes under different editing scales.

**Comment by rohitgandikota** [comment] 2023-11-23 16:00
Yes, and the way we do it is:
1. We set the lora scale to 0 for the first `t` timesteps
2. Then, for the rest of the inference, we set the scale to the desired value.

This did the trick

**Comment by hkunzhe** [comment] 2023-11-23 16:04
@rohitgandikota, A more intuitive way to describe this technique is to assume that the original scheduler has a timesteps of 1000. If you set the `start_noise=800` and perform 50 steps of denoising, which means not using LORA for the first 10 steps (50*0.2=10 steps), and using LORA for the subsequent 40 steps (50*0.8=40 steps). Is my understanding correct?

**Comment by rohitgandikota** [comment] 2023-11-23 16:06
Perfect. Yes!

**Comment by hkunzhe** [comment] 2023-11-23 16:08
@rohitgandikota, Great! I have a rough idea of how to implement the SDEdit technique in the Web UI, and I'll spend some time tomorrow to work on it.

**Comment by rohitgandikota** [comment] 2023-11-23 16:09
That is awesome! Thanks for looking into this. Really appreciate it!

**Comment by 0xdevalias** [comment] 2023-11-23 21:46
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/14064

**Comment by hkunzhe** [comment] 2023-11-24 02:20
This plugin [cheald/sd-webui-loractl](https://github.com/cheald/sd-webui-loractl) is able to approximate the inference process used in concept sliders with the SDEdit technique. Taking `age.pt` as an example, the prompt word is "a portrait of a young beautiful woman". From the results below, it can be seen that  the lora scale changes as expected during the inference process, making the editing result more controllable and smooth.
<img width="892" alt="image" src="https://github.com/rohitgandikota/sliders/assets/30763967/051a8f6b-e4fc-4356-8785-374354d479a3">

**Comment by rohitgandikota** [comment] 2023-11-24 02:24
This is awesome!

**Comment by rohitgandikota** [comment] 2023-11-24 02:28
Oh wait a minute, if the slider is changing the structure drastically for scale 3, maybe it is not enough SDEdit? Could you tune the tilmestep variable at which the slider is being turned on ?

**Comment by hkunzhe** [comment] 2023-11-24 02:38
@rohitgandikota I've uploaded the picture "LoRA weight in all steps". This should be the same as what I've said here https://github.com/rohitgandikota/sliders/issues/2#issuecomment-1824665190, if I'm not mistaken.

**Comment by rohitgandikota** [comment] 2023-11-24 02:44
Oh yeah, I meant - when you are using large lora scales, you can maybe do the transition in step 15 or 20. It would preserve the structure more and increase the edit strength.

**Comment by hkunzhe** [comment] 2023-11-24 02:52
@rohitgandikota the tilmestep variable at which the slider is being turned on can be certainly tuned. I just provide a simple example. It seems the third picture misled you; I have already edited its content.

**Comment by rohitgandikota** [comment] 2023-11-24 02:55
I see - I just wanted to see if the slider plugin you have can recreate our results. Just curious. Would love if you can provide an example with alpha=1, 2, 3 with start noise at time=20 ?

Thank you so much! This is very cool

**Comment by hkunzhe** [comment] 2023-11-24 03:04
<img width="633" alt="image" src="https://github.com/rohitgandikota/sliders/assets/30763967/363af8a8-e599-4275-a6f4-c6420ba001a9">
It seems that If we do transition too late, it will not have the editing effect.

**Comment by rohitgandikota** [comment] 2023-11-24 03:19
Awesome! So the 0.15 thing seems to work with scale 3. Thanks for the update

**Comment by rohitgandikota** [comment] 2023-11-24 03:23
@hkunzhe, I am not very familiar with the UIs, do you think this can be easily applied to the comfyUI as well ?

**Comment by hkunzhe** [comment] 2023-11-24 07:21
@rohitgandikota, I am also completely unfamiliar with comfyui. I think this plugin cannot be used in comfyui, it depends on the comfyui community.

**Comment by FurkanGozukara** [comment] 2023-11-24 21:47
@hkunzhe lets say I have installed this extension : https://github.com/cheald/sd-webui-loractl

I downloaded [pixar_style.pt](https://sliders.baulab.info/weights/xl_sliders/pixar_style.pt) into my lora folder

so how do I prompt with that extension?

**Comment by mofos** [comment] 2023-11-25 21:34
got it working in ComfyUI without any Custom node 
![srgdgg](https://github.com/rohitgandikota/sliders/assets/44880207/fcf4a27f-5c4e-4700-a773-b02acb3d817c)

**Comment by mofos** [comment] 2023-11-25 21:37
Using eyesize.pt. drag and drop this image to the comfyUI to check my workflow
![ComfyUI_00145_](https://github.com/rohitgandikota/sliders/assets/44880207/94c206d8-5890-4e7d-879b-4bae5421af31)

**Comment by rohitgandikota** [comment] 2023-11-25 21:50
Awesome! @mofos, can you describe how you were able to achieve this? Did you implement the inference method we introduced with sliders in comfy?

**Comment by mofos** [comment] 2023-11-25 22:45
its Simply, used a node called Ksampler Advance. did a 20 Step process with the 0 to 10 being with the base model ( Juggernaut-xl) and 10 to 20 steps was achieved with the LoRa + base model. eyesize.pt seems like LoRa mode for make eyes small, gave it a strength of -2 and it gave me big eyes 

 if you don't have Comfy UI running just duplicate my hugging face space and drag the image above, to the interface and press queue prompt at the top right corner to see the flow (https://huggingface.co/spaces/zac/ComfyUI)

**Comment by mofos** [comment] 2023-11-25 22:50
![3452ergrfgsd](https://github.com/rohitgandikota/sliders/assets/44880207/fc275dd4-4249-49c4-8cac-63dc7e09840c)

**Comment by rohitgandikota** [comment] 2023-11-25 23:21
> its Simply, used a node called Ksampler Advance. did a 20 Step process with the 0 to 5 being with the base model ( Juggernaut-xl) and 5 to 20 steps was achieved with the LoRa + base model. BTW, eyesize.pt seems like LoRa mode for making eyes small, gave it a strength of -2 and it gave me big eyes
> 
> if you don't have Comfy UI running just duplicate my hugging face space and drag the image above, to the interface and press queue prompt at the top right corner to see the flow (https://huggingface.co/spaces/zac/ComfyUI)

This is so cool! the url you shared doesn't seem to work. I am getting a 404 error

**Comment by mofos** [comment] 2023-11-25 23:38
My Bad, Its a private space but i just made it public, also added eyesize.pt to the docker file. but ill suggest to make some changes since the Docker downloads a lot of models during its build ( i know it a really bad practice). alternatively you can check this space (https://huggingface.co/spaces/SpacesExamples/ComfyUI) but you'll need duplicate and add your LoRa to the space and docker.

**Comment by rohitgandikota** [comment] 2023-11-26 00:06
Awesome! Thanks @mofos!

**Comment by rohitgandikota** [comment] 2023-11-26 00:07
@hkunzhe, could you please let us know how you used a1111 for sliders?

**Comment by FurkanGozukara** [comment] 2023-11-26 00:07
> @hkunzhe, could you please let us know how you used a1111 for sliders?

I am waiting this info too

I want to test on Automatic1111

**Comment by hkunzhe** [comment] 2023-11-26 01:59
@FurkanGozukara , 

> @hkunzhe lets say I have installed this extension : https://github.com/cheald/sd-webui-loractl
> 
> I downloaded [pixar_style.pt](https://sliders.baulab.info/weights/xl_sliders/pixar_style.pt) into my lora folder
> 
> so how do I prompt with that extension?

`<lora:pixar_style:0@0, 0@0.2, 3@0.2, 3@1>`

**Comment by FurkanGozukara** [comment] 2023-11-26 20:41
> @FurkanGozukara ,
> 
> > @hkunzhe lets say I have installed this extension : https://github.com/cheald/sd-webui-loractl
> > I downloaded [pixar_style.pt](https://sliders.baulab.info/weights/xl_sliders/pixar_style.pt) into my lora folder
> > so how do I prompt with that extension?
> 
> `<lora:pixar_style:0@0, 0@0.2, 3@0.2, 3@1>`

thank you so much

what do those 0@0, 0@0.2, 3@0.2 and 3@1 means?

**Comment by rohitgandikota** [comment] 2023-11-28 23:56
Closing this issue - Shoutout to @hkunzhe and @mofos!!! 

feel free to reopen if issue occurs with the current solutions

**Closed by rohitgandikota** 2023-11-28 23:56 UTC

**Comment by FurkanGozukara** [comment] 2023-11-29 00:12
<lora:pixar_style:0@0, 0@0.2, 3@0.2, 3@1>

could you tell what does these means? @rohitgandikota

**Comment by rohitgandikota** [comment] 2023-11-29 00:16
Oh, I am not completely sure since I am not very familiar with A1111. But my guess is that `0@0` means 0 scale at timestep 0. So when we want to switch at `0.2T` (where `T` is the scheduler total timestep), they mention it as `0@0.2, 3@0.2`. It might mean that the switch is happening at 0.2T from scale 0 to scale 3. @hkunzhe can confirm my guess.

This sounds like the most probable explanation to me.

**Comment by rohitgandikota** [comment] 2023-11-29 00:21
That would be amazing! Once you publish it , share it with us - we will include it on our website

**Comment by filliptm** [comment] 2023-11-29 10:29
<img width="1709" alt="Screenshot 2023-11-28 055651" src="https://github.com/rohitgandikota/sliders/assets/55672949/320f711e-fb9d-41ee-87f7-1f58af87be6d">


I trained a skin slider lora, tested it in comfy for the XY plots, works fine. nothing fancy

**Comment by hkunzhe** [comment] 2023-11-29 10:45
@filliptm awesome! text sliders or image sliders?

**Comment by filliptm** [comment] 2023-11-29 11:12
> @filliptm awesome! text sliders or image sliders?

this was text, i def wanna try out the image next

**Comment by ameen-roayan** [comment] 2023-12-01 14:59
> got it working in ComfyUI without any Custom node ![srgdgg](https://private-user-images.githubusercontent.com/44880207/285616909-fcf4a27f-5c4e-4700-a773-b02acb3d817c.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDMwNTUsIm5iZiI6MTcwMTQ0Mjc1NSwicGF0aCI6Ii80NDg4MDIwNy8yODU2MTY5MDktZmNmNGEyN2YtNWM0ZS00NzAwLWE3NzMtYjAyYWNiM2Q4MTdjLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE0NTkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkY2U2OTQyMjEzZWIzNGMwMzMxNTM2YmEzNGRjN2Y1YTJjMzBhNTcxMTc4NGNjN2Q5ZjhlM2I3ZmNlM2NkZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e_bh1DmsK6m45fy4F-WRgiJwvR-sbmy8z1J3XhFG7cM)

Where do we get the file from ? the eyesize.pt

**Comment by rohitgandikota** [comment] 2023-12-01 16:01
https://sliders.baulab.info/weights/xl_sliders/

**Comment by aretius** [comment] 2024-09-14 16:44
Hey @filliptm 
Its quite a old comment but how did you test the LORA in comfy UI?
